config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  root 'static_pages#index'

  get '/help', to: 'static_pages#help'
  get 'signup', to: 'users#new'
  get 'logout', to: 'users#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save {self.email = email.downcase}

  validates :first_name, presence: true, length: {minimum: 3, maximum: 20}
  validates :last_name, presence: true, length: {minimum: 3, maximum: 20}

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 10, maximun: 50}, format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
        end

        def show
          @user = User.find(params[:id])
        end

        def new
          @user = User.new
        end

        def create
          @user = User.new(user_params)
          if @user.save
            flash[:success] = 'User created successfully'
            redirect_to @user
          else
            render 'new'
        end
      end

      private

      def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.last_name)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row small-up-1 medium-up-3">
    <div class="column">
      <h4>Contact Info</h4>
      <hr>
      <a href="#"><span>Phone:</span> 601128758278</a>
      <a href="#"><span>Email:</span> alex@company.com</a>
      <a href="#"><span>Address:</span> 123 JackMa House</a>
    </div>

    <div class="column">
      <h4>Site Map</h4>
      <hr>
      <a href="#">About Us</a>
      <a href="#">Services</a>
      <a href="#">Contact Us</a>
    </div>
    <div class="column">
      <h4>Social Media</h4>
      <hr>
      <a href="#">Facebook</a>
      <a href="#">Twitter</a>
      <a href="#">Instagram</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="top-bar"
  <div class="row">

    <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="example-menu"></button>
    <div class="title-bar-title">Menu</div>
    </div>

    <div class="top-bar" id="example-menu">
    <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
    <li class="menu-text">Todo</li>
      <li>
        <a href="#">Account</a>
        <ul class="menu vertical">
          <li><a href="#">Sign In</a></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <li><a href="#">Logout</a></li>

        </ul>
      </li>

    </ul>
    </div>
    <div class="top-bar-right">
    <ul class="menu">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Help', help_path %></a></li>
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
    </div>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

<div class= "content">
    <%=  render 'layouts/navbar' %>

    <% if flash[:success] %>
    <div class="success callout" data-closable>
      <%= display_flash_messages %>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%end%>


    <%= yield %>


      <%=  render 'layouts/footer' %>
        </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert callout">
    The form contains <%= pluralize(@user.errors.count, 'error') %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
        <%end%>
      </ul>
    <%end%>

app/views/static_pages/help.html.erb
<div class = "row">
<div class = "small-12 medium-12 large-12 columns">    
<h1 class='title'> Welcome to Authentication Help Page </h1>
</div>

app/views/static_pages/index.html.erb
<div class = "row">
<div class = "small-12 medium-12 large-12 columns">
<h1 class='title'> Welcome to Todo Apps </h1>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up') %>

  <div class = "row">
    <div class ="small-10 small-centered medium-4 medium-centered columns">
      <h2 id= "sign_up" > Sign Up </h2>
      <%= form_for (@user) do |f| %>




        <%= f.text_field :first_name %>


        <%= f.text_field :last_name %>


        <%= f.email_field :email %>


        <%= f.password_field :password %>


        <%= f.password_field :password_confirmation %>

        <%= f.submit 'Create Account', class: "expanded button" %>
      <%end%>
    </div>
  </div>

app/views/users/show.html.erb
<%= provide(:title, @user.last_name) %>

      <div class="row">
        <div class="small-12 medium-12 columns">
         <h1 class="title">
          <%= gravatar_for @user %>
          <%= @user.first_name + ' ' + @user.last_name %>
          </h1>
        </div>
      </div>